---
# --- NETWORK TOPOLOGY & ADDRESSING ---
network:
  prefixes:
    ipv4: "10.50.99.0/24"
    ipv6: "fd99:10:50:99::/64"

  honeywall:
    wan: # Internet-facing interface
      interface: "enp2s0"
      ipv4: "172.31.99.129/24"
      ipv6: "fd99:10:50:99::5/64"
    lan: # Internal or Dummy interface (ltn0 in single-node)
      interface: "ltn0"
      ipv4: "10.50.99.6/24"
      ipv6: "fd99:10:50:99::6/64"

  collectors:
    collector_01:
      ipv4: "10.50.99.10/24"
      ipv6: "fd99:10:50:99::10/64"
      port: 48123

  sensors:
    sensor_01:
      ipv4: "10.50.99.100/24"
      ipv6: "fd99:10:50:99::100/64"
