---
# --- COLLECTOR USER ---
- name: "Manage collector user group"
  become: true
  group:
    gid: "{{ system.users.collector.uid }}"
    name: "{{ system.users.collector.name }}"
    state: present

- name: "Manage collector system user"
  become: true
  user:
    uid: "{{ system.users.collector.uid }}"
    name: "{{ system.users.collector.name }}"
    group: "{{ system.users.collector.name }}"
    shell: /usr/sbin/nologin
    create_home: false
    system: true
    state: present

- name: "Add Vector user to collector group"
  become: true
  ansible.builtin.user:
    name: vector
    groups: "{{ system.users.collector.name }}"
    append: true
  notify: "Restart Vector"

# -- COLLECTOR DIRECTORIES ---
- name: "Create collector config directory"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - /etc/lantana/collector

- name: "Create datalake directory"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ system.users.collector.name }}"
    group: "{{ system.users.collector.name }}"
    mode: "0770" # vector user is part of collector group and manages the data lake too
  loop:
    - /var/lib/lantana/datalake
    - /var/lib/lantana/datalake/bronze
    - /var/lib/lantana/datalake/silver
    - /var/lib/lantana/datalake/gold

# --- SECRETS FILE ---
- name: Deploy API credentials template
  become: true
  ansible.builtin.template:
    src: secrets.json.j2
    dest: /etc/lantana/collector/secrets.json
    owner: "{{ system.users.collector.name }}"
    group: "{{ system.users.collector.name }}"
    mode: "0600"
  no_log: true

# --- LANTANA-PRUNE DEPLOYMENT ---
- name: "Deploy lantana-prune script"
  become: true
  ansible.builtin.copy:
    src: lantana-prune
    dest: /usr/local/sbin
    owner: root
    group: root
    mode: "0644"

- name: "Add periodic pruning"
  become: true
  ansible.builtin.copy:
    dest: /etc/cron.d/lantana-prune
    content: "15 0 * * * root /usr/local/sbin/lantana-prune\n"
    mode: "0644"

# --- LOG RECEIVER ---
- name: "Deploy Vector receiver configuration"
  become: true
  ansible.builtin.template:
    src: receive.vector.yaml.j2
    dest: /etc/vector/conf.d/receive.yaml
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart Vector"
