---
- name: "Deploy multi-node operation: Honeywall"
  hosts:
    - honeywall_nodes
  roles:
    - role: base
      tags: [base]
    - role: profile_honeywall
      tags: [nftables, suricata]
    - role: firewall
      tags: [nftables]
    - role: suricata
      tags: [suricata]

- name: "Deploy multi-node operation: Collector"
  hosts:
    - collector_nodes
  roles:
    - role: base
      tags: [base]
    - role: profile_collector
      tags: [collector]

- name: "Deploy multi-node operation: Low-interaction sensor"
  hosts:
    - sensor_low_nodes
  roles:
    - role: base
      tags: [base]
    - role: profile_sensor_low
      tags: [honeypots]

- name: "Deploy multi-node operation: High-interaction sensor"
  hosts:
    - sensor_high_nodes
  roles:
    - role: base
      tags: [base]
    - role: profile_sensor_high
      tags: [honeypots]
