---
- name: "Deploy single-node sensor"
  hosts: single_nodes
  roles:
    - role: base
      tags: [base]
    - role: profile_honeywall
      tags: [nftables, suricata]
    - role: profile_collector
      tags: [collector]
    - role: profile_sensor_low
      tags: [honeypots]
    - role: network
      tags: [network]
    - role: firewall
      tags: [nftables]
    - role: suricata
      tags: [suricata]
