---
- name: "Deploy low-interaction honeypots"
  hosts:
    - single_nodes
    - sensor_low_nodes
  tasks:
    - name: "Deploy honeypot roles"
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ sensor_honeypots | default([]) }}"
      tags: [honeypots]
#
# - name: "Setup high-interaction sensors"
#   hosts: sensor_high_nodes
#   roles:
#     - vuln_ssh
