# /etc/rsyslog.d/10-nftables.conf
# Managed by Ansible

:msg, contains, "[LANTANA_" action(
    type="omfile"
    File="/var/log/lantana/honeywall/nftables/firewall.log"
    FileCreateMode="0644"
    DirCreateMode="0755"
)
& stop
