---
all:
  children:
    single_nodes:
      hosts:
        sn-01: # This automatically becomes {{ inventory_hostname }}
          ansible_host: 172.31.99.129
          lantana_profile: "single_node_sensor"
          sensor_honeypots:
            - cowrie
            # - dionaea
