---
# --- BASIC PACKAGES ---
- name: "Update apt cache"
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: "Install basic packages"
  become: true
  ansible.builtin.apt:
    name:
      - cron
      - rsyslog

# --- BASIC SYSTEM SETUP ---
- name: "Set system timezone to UTC"
  become: true
  ansible.builtin.timezone:
    name: Etc/UTC
  notify:
    - Restart rsyslog
    - Restart cron

- name: "Ensure hostname is resolvable in /etc/hosts"
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} LANTANA HOSTNAME BLOCK - MANAGED BY ANSIBLE"
    block: |
      127.0.1.1 {{ inventory_hostname }}
      ::1 localhost ip6-localhost ip6-loopback {{ inventory_hostname }}

- name: "Configure system hostname"
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: "Deploy system MOTD banner"
  become: true
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"

# -- BASE DIRECTORIES ---
- name: "Create base directories"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - /etc/lantana
    - /etc/lantana/logrotate.d
    - /etc/lantana/logrotate.d/00_00
    - /var/log/lantana
    - /var/lib/lantana

- name: "Setup log rotation"
  become: true
  ansible.builtin.copy:
    dest: /etc/cron.d/lantana-logs
    content: |
      # Process all logs scheduled for 00:00 (Midnight)
      0 0 * * * root /usr/sbin/logrotate -f /etc/lantana/logrotate.d/00_00/*

    mode: "0644"

- name: "Deploy SSH"
  include_tasks: ssh.yml

- name: "Deploy Vector"
  include_tasks: vector.yml
