# /etc/rsyslog.d/20-audit.conf
# Managed by Ansible

input(type="im_audit")
action(
    type="omfile"
    File="/var/log/lantana/honeywall/audit/audit.log"
    FileCreateMode="0644"
    DirCreateMode="0755"
)
& stop
