# /etc/rsyslog.d/30-auth.conf
# Managed by Ansible

auth,authpriv.* action(
    type="omfile"
    File="/var/log/lantana/honeywall/auth/auth.log"
    FileCreateMode="0644"
    DirCreateMode="0755"
)
& stop
