---
# --- FIREWALL LOGGING ---
- name: "Setup firewall connections logging"
  become: true
  ansible.builtin.copy:
    src: 10-nftables.conf
    dest: /etc/rsyslog.d/
    owner: root
    group: root
    mode: "0644"
  notify: "Restart rsyslog"

- name: "Setup log rotation of firewall connections"
  become: true
  ansible.builtin.copy:
    src: firewall.logrotate
    dest: /etc/lantana/logrotate.d/00_00/firewall
    owner: root
    group: root
    mode: "0644"

# --- MODE SPECIFIC CONFIGURATION ---
- name: "Configure single node firewall"
  include_tasks: single_node.yml
  when: lantana.mode == "single"

- name: "Configure multi node firewall"
  include_tasks: multi_node.yml
  when: lantana.mode == "multi"
